let tank_img = new Image();
let tank_img1 = new Image();
let tank_img2 = new Image();
let fire_img = new Image();

let bush = new Image();
let small_bush = new Image();
let bg_tileSet = new Image();
let lakdi = new Image();
let gate = new Image();
let bult_blue = new Image();
let bult_black = new Image();
let bult_red = new Image();
let blast1 = new Image();
let blast2 = new Image();
let blast3 = new Image();
let blast4 = new Image();
let blast5 = new Image();

let crateWood = new Image();

tank_img.src = "images/Tanks/tank_blue.png";
tank_img2.src = "images/Tanks/tank_red.png";
bult_black.src = "images/world/bulletDark1.png";
bult_red.src= "images/world/bulletRed1.png";
bush.src= "images/world/treeGreen_large.png";
bg_tileSet.src = "images/world/terrainTiles_retina.png";
small_bush.src = "images/world/treeGreen_small.png";
lakdi.src = "images/world/treeGreen_twigs.png";
gate.src = "images/world/fenceRed.png";
tank_img1.src = "images/Tanks/tank_green.png";
bult_blue.src = "images/world/bulletBlue1.png";
fire_img.src = "images/Tanks/shotLarge.png";
blast1.src = "images/world/explosion1.png";
blast2.src = "images/world/explosion2.png";
blast3.src = "images/world/explosion3.png";
blast4.src = "images/world/explosion4.png";
blast5.src = "images/world/explosion5.png";
crateWood.src = "images/world/crateWood.png";